source('./dependencies.R', local = T)
source('./library.R', local = T)
source('./parameters.R', local = T)

genStartTime <- Sys.time()
source('./generator.R', local = T)
genEndTime <- Sys.time()
analysisStartTime <- Sys.time()
source('./analysis.R', local = T)
analysisEndTime <- Sys.time()
cat("Generator ")
print(genEndTime - genStartTime)
cat("Analysis ")
print(analysisEndTime - analysisStartTime)
saveRDS(simData, "simData.rds")
